title:             Krystal Pharma Engineering
email:             vijay@krystalpharma.com
author:            Krystal Pharma
#baseurl:               "/"
#url:               "https://krystalpharma.github.io"

# Social Profiles
twitter_username:  PharmaKrystal
github_username:   krystalpharma
facebook_username: krystalpharma

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
